# Browser Config
browser=chrome
headless=false

# Application
baseURL=https://sauce-demo.myshopify.com/

# Credentials
username=admin@test.com
password=secret123

# Timeouts
implicitWait=10
explicitWait=20

# Reporting
reportPath=reports/ExtentReport.html
screenshotPath=screenshots/